# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bootsnap', require: false
gem 'csv'
gem 'importmap-rails'
gem 'jbuilder'
gem 'kamal', require: false
gem 'mat_views', path: '../mat_views'
gem 'pg', '~> 1.1'
gem 'propshaft'
gem 'puma', '>= 5.0'
gem 'rails', '~> 8.1.0'
gem 'solid_cable'
gem 'solid_cache', '>= 1.0.8'
gem 'solid_queue'
gem 'stimulus-rails'
gem 'thruster', require: false
gem 'turbo-rails'
gem 'tzinfo-data', platforms: %i[windows jruby]
group :development, :test do
  gem 'brakeman', require: false
  gem 'debug', platforms: %i[mri windows],
               require: 'debug/prelude'
  gem 'faker'
  gem 'rubocop-capybara', require: false
  gem 'rubocop-rails', require: false
end

group :development do
  gem 'ruby-lsp', require: false
  gem 'ruby-lsp-rails', require: false
  gem 'ruby-lsp-rspec', require: false
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
end
