---
detectors:
  UncommunicativeVariableName:
    accept:
      - e
      - t
  TooManyStatements:
    enabled: true
    max_statements: 20
  BooleanParameter:
    enabled: false
  ControlParameter:
    enabled: false
  UtilityFunction:
    public_methods_only: true
  LongParameterList:
    enabled: true
    max_params: 5
  NilCheck:
    enabled: true
    exclude:
      - MatViews::CreateViewJob#force?
  FeatureEnvy:
    enabled: true
    exclude:
      - MatViews::Services::BaseService#pg_idle?
      - CreateMatViewRuns#change
      - CreateMatViewDefinitions#change
      - CreateUsers#change
      - CreateAccounts#change
      - CreateEvents#change
      - CreateSessions#change
  TooManyMethods:
    enabled: true
    exclude:
      - MatViews::Services::BaseService
  DuplicateMethodCall:
    enabled: true
    exclude:
      - MatViews::ApplicationJob#record_run
  ManualDispatch:
    enabled: true
    exclude:
      - MatViews::Services::BaseService#pg_idle?
  Attribute:
    enabled: true
    exclude:
      - MatViews::Configuration#job_adapter
      - MatViews::Configuration#job_queue
      - MatViews::Services::BaseService#request
      - MatViews::Services::BaseService#response
directories:
  "spec":
    DuplicateMethodCall:
      enabled: false
    UtilityFunction:
      enabled: false
