---
detectors:
  UncommunicativeVariableName:
    accept:
      - e
      - t
      - _
  TooManyStatements:
    enabled: true
    max_statements: 20
  BooleanParameter:
    enabled: false
  ControlParameter:
    enabled: false
  TooManyConstants:
    enabled: true
    max_constants: 30
  UtilityFunction:
    public_methods_only: true
    exclude:
      - MatViews::Admin::DefaultAuth#mat_views_current_user
      - MatViews::Admin::AuthBridge#host_auth_module
      - MatViews::Admin::UiHelper#mv_button_classes
      - MatViews::Admin::DatatableHelper#pagination_window
      - MatViews::Admin::LocalizedDigitHelper#localized_numbers
      - MatViewsPaginate#total_pages
  LongParameterList:
    enabled: true
    max_params: 10
  NilCheck:
    enabled: true
    exclude:
      - MatViews::CreateViewJob#force?
      - MatViews::Admin::MatViewDefinitionsController#normalize_array_field
  FeatureEnvy:
    enabled: true
    exclude:
      - MatViews::Services::BaseService#pg_idle?
      - CreateMatViewRuns#change
      - CreateMatViewDefinitions#change
      - CreateUsers#change
      - CreateAccounts#change
      - CreateEvents#change
      - CreateSessions#change
      - MatViews::Admin::MatViewDefinitionsController#normalize_array_field
      - MatViews::Admin::UiHelper#link_options
      - MatViews::Admin::UiHelper#mv_badge
      - MatViews::Admin::UiHelper#mv_drawer_action_button
      - MatViews::Admin::UiHelper#mv_tab_link
  TooManyMethods:
    enabled: true
    exclude:
      - MatViews::Services::BaseService
      - MatViews::Admin::MatViewDefinitionsController
  DuplicateMethodCall:
    enabled: true
    exclude:
      - MatViews::ApplicationJob#record_run
      - MatViews::Admin::MatViewDefinitionsController#index_dt_config
      - MatViews::Admin::MatViewRunsController#index_dt_config
      - MatViews::Admin::DatatableHelper#pagination_window
      - MatViews::Admin::DatatableHelper#parse_header_to_params
  ManualDispatch:
    enabled: true
    exclude:
      - MatViews::Services::BaseService#pg_idle?
      - MatViews::Admin::UiHelper#mv_icon
      - MatViews::Admin::DatatableHelper#dt_apply_filter
  Attribute:
    enabled: true
    exclude:
      - MatViews::Configuration#job_adapter
      - MatViews::Configuration#job_queue
      - MatViews::Services::BaseService#request
      - MatViews::Services::BaseService#response
      - MatViews#importmap
      - MatViews::Configuration#admin_ui
      - MatViews::Admin::DefaultAuth::SampleUser#email
      - MatViews::Services::BaseService#use_transaction
  InstanceVariableAssumption:
    enabled: true
    exclude:
      - MatViews::Admin::ApplicationController
      - MatViews::Admin::MatViewDefinitionsController
      - MatViews::Admin::MatViewRunsController
      - MatViews::Admin::PreferencesController
  MissingSafeMethod:
    enabled: true
    exclude:
      - MatViews::Admin::PreferencesController
  TooManyInstanceVariables:
    enabled: true
    max_instance_variables: 10
  DataClump:
    enabled: false
directories:
  "spec":
    DuplicateMethodCall:
      enabled: false
    UtilityFunction:
      enabled: false
