plugins:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-rake
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: true

Metrics/MethodLength:
  Max: 20
RSpec/MultipleExpectations:
  Max: 5
