plugins:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-rake
  - rubocop-factory_bot
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: true
  Exclude:
    - .vscode/**/*
    - vendor/**/* # ignore vendored gems
    - vendor/bundle/**/* # (explicitly, for Bundler’s path)

Metrics/MethodLength:
  Max: 50
Metrics/ModuleLength:
  Max: 250
Metrics/BlockLength:
  Max: 50
Metrics/ParameterLists:
  Max: 10
RSpec/MultipleExpectations:
  Max: 20
RSpec/ExampleLength:
  Max: 50
Layout/LineLength:
  Max: 160
RSpecRails/InferredSpecType:
  Enabled: false
Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Max: 30
RSpec/MultipleMemoizedHelpers:
  Max: 15
Metrics/CyclomaticComplexity:
  Max: 10
RSpec/NestedGroups:
  Max: 5
Metrics/PerceivedComplexity:
  Max: 15
RSpec/ScatteredSetup:
  Exclude:
    - spec/features/**/*
