plugins:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-rake
  - rubocop-factory_bot
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: true

Metrics/MethodLength:
  Max: 20
RSpec/MultipleExpectations:
  Max: 5
RSpec/ExampleLength:
  Max: 15
Layout/LineLength:
  Max: 150
RSpecRails/InferredSpecType:
  Enabled: false
