plugins:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-rake
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: true

Metrics/MethodLength:
  Max: 20
RSpec/MultipleExpectations:
  Max: 10
RSpec/ExampleLength:
  Max: 15
Layout/LineLength:
  Max: 150
RSpecRails/InferredSpecType:
  Enabled: false
Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Max: 25
RSpec/MultipleMemoizedHelpers:
  Max: 10
Metrics/CyclomaticComplexity:
  Max: 10
