# frozen_string_literal: true

# Copyright Codevedas Inc. 2025-present
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

source 'https://rubygems.org'

gemspec

gem 'bootsnap', require: false
gem 'pg'
gem 'propshaft'
gem 'puma'

group :development, :test do
  # Start debugger with binding.b [https://github.com/ruby/debug]
  # gem "debug", ">= 1.0.0"
  gem 'danger'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'faraday-retry'
  gem 'generator_spec'
  gem 'importmap-rails'
  gem 'reek'
  gem 'rspec-rails'
  gem 'rubocop-capybara'
  gem 'rubocop-factory_bot'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'rubocop-rspec_rails'
  gem 'shoulda-matchers'
  gem 'stimulus-rails'
  gem 'turbo-rails'
end

group :test do
  gem 'capybara'
  gem 'capybara-screenshot', require: false
  gem 'database_cleaner-active_record'
  gem 'resque'
  gem 'selenium-webdriver'
  gem 'sidekiq'
  gem 'simplecov', require: false
  gem 'simplecov-console', require: false
  gem 'webdrivers', require: false
end

group :development do
  gem 'ruby-lsp', require: false
  gem 'ruby-lsp-rails', require: false
  gem 'ruby-lsp-rspec', require: false
end
