default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mat_views_demo_development
test:
  <<: *default
  database: mat_views_demo_test
production:
  primary: &primary_production
    <<: *default
    database: mat_views_demo_production
    username: mat_views_demo
    password: <%= ENV["MAT_VIEWS_DEMO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: mat_views_demo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mat_views_demo_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: mat_views_demo_production_cable
    migrations_paths: db/cable_migrate
