name: CI
permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci
  cancel-in-progress: true

env:
  RUBY_VERSION: 3.4.3
  APP_DIR: ${{ github.workspace }}/mat_views

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: ${{ env.APP_DIR }}
      - run: bundle info rake

  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: ${{ env.APP_DIR }}
      - name: RuboCop
        run: bin/rubocop -f github

  reek:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: ${{ env.APP_DIR }}
      - name: Reek
        run: bin/reek

  tests:
    needs: [lint, reek]
    uses: ./.github/workflows/ruby-tests.yml
    with:
      ruby_version: ${{ env.RUBY_VERSION }}
      app_dir: ${{ env.APP_DIR }}
      rspec_task: "bin/rspec-unit"
      need_seed: true
      need_firefox: false
      upload_coverage: true
      qlty_coverage: true
    secrets:
      QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}

  e2e_tests:
    needs: [lint, reek]
    uses: ./.github/workflows/ruby-tests.yml
    with:
      ruby_version: ${{ env.RUBY_VERSION }}
      app_dir: ${{ env.APP_DIR }}
      rspec_task: "bin/rspec-e2e"
      need_seed: false
      need_firefox: true
      upload_coverage: false
