name: CI
permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci
  cancel-in-progress: false

env:
  RUBY_VERSION: 3.4.3
  APP_DIR: ${{ github.workspace }}/mat_views

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: ${{ env.APP_DIR }}
      - run: bundle info rake

  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: ${{ env.APP_DIR }}
      - name: RuboCop
        run: bin/rubocop -f github

  reek:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: ${{ env.APP_DIR }}
      - name: Reek
        run: bin/reek

  tests:
    needs: [lint, reek]
    uses: ./.github/workflows/ruby-unit-tests.yml
    with:
      rspec_task: bin/rspec-unit --profile 10
      upload_coverage: true
    secrets:
      QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}
  e2e_tests:
    permissions:
      contents: read
    needs: [lint, reek]
    uses: ./.github/workflows/ruby-e2e-tests.yml
    with:
      rspec_task: bin/rspec-e2e --profile 10
  upsert_screenshots_comment:
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    needs: [e2e_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Upsert comment with app screenshots link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          header: 📸 MatViews Admin App Screenshots
          message: |
            App screenshots from the latest e2e test run are available.
            | Name | Link |
            | ---- | ---- |
            | Commit | ${{ github.event.pull_request.head.sha }} |
            | Workflow | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | Screenshots | ${{ needs.e2e_tests.outputs.app_screenshots_url }} |
