permissions:
  contents: read
name: Release

on:
  push:
    tags:
      - v*

jobs:
  test:
    permissions:
      contents: read
    name: Run RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libpq-dev libyaml-dev pkg-config google-chrome-stable
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: true
          working-directory: ${{ github.workspace }}/mat_views
      - name: Run tests
        working-directory: ${{ github.workspace }}/mat_views
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
          # REDIS_URL: redis://localhost:6379/0
        run: bin/rails db:test:prepare && bin/rails db:seed && bin/rspec --format documentation --color --profile

  push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      id-token: write
    environment: release
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
          working-directory: ${{ github.workspace }}/mat_views
      - name: Configure RubyGems Credentials
        uses: rubygems/configure-rubygems-credentials@main
      - name: Release
        run: |
          cd mat_views
          gem build mat_views.gemspec
          gem push mat_views-*.gem
