name: Ruby Tests (reusable)

on:
  workflow_call:
    inputs:
      gecko_driver_version:
        required: false
        type: string
        default: "0.36.0"
      rspec_task:
        required: true
        type: string
        description: "Command to run tests (e.g., bin/rspec-unit or bin/rspec-e2e)"
      require_browser:
        required: false
        type: boolean
        default: false
      upload_coverage:
        required: false
        type: boolean
        default: true
      qlty_coverage:
        required: false
        type: boolean
        default: false
    secrets:
      QLTY_COVERAGE_TOKEN:
        required: false
env:
  RUBY_VERSION: 3.4.3
  APP_DIR: ${{ github.workspace }}/mat_views
jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    services:
      firefox:
        if: ${{ inputs.require_browser }}
        image: selenium/standalone-firefox:latest
        ports: ["4444:4444"]
        options: >-
          --health-cmd="curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            build-essential git libpq-dev libyaml-dev pkg-config firefox
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: ${{ env.APP_DIR }}
      - name: Cache Bootsnap
        uses: actions/cache@v4
        with:
          path: ${{ env.APP_DIR }}/spec/dummy/tmp/cache
          key: bootsnap-${{ runner.os }}-${{ env.RUBY_VERSION }}-${{ hashFiles('**/Gemfile.lock') }}
      - name: Prepare database
        working-directory: ${{ env.APP_DIR }}
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: |
          bin/rails db:drop || true
          bin/rails db:create
          bin/rails db:schema:load
      - name: Run unit tests
        if: ${{ !inputs.require_browser }}
        working-directory: ${{ env.APP_DIR }}
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: ${{ inputs.rspec_task }}
      - name: Run e2e tests
        if: ${{ inputs.require_browser }}
        working-directory: ${{ env.APP_DIR }}
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: ${{ inputs.rspec_task }}
      - name: Upload SimpleCov report
        if: ${{ inputs.upload_coverage }}
        uses: actions/upload-artifact@v4
        with:
          name: simplecov-report
          path: ${{ env.APP_DIR }}/coverage
          if-no-files-found: ignore

      - name: Publish coverage to Qlty
        if: ${{ inputs.qlty_coverage }}
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ${{ env.APP_DIR }}/coverage/.resultset.json

      - name: Keep screenshots from failed system tests
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ${{ env.APP_DIR }}/tmp/screenshots
          if-no-files-found: ignore
